name: Daily News Digest

on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate daily digest
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
        run: python daily-digest.py

      - name: Commit and push changes (optional, for record keeping)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Feat: Automated daily news digest update 🤖'